### ISSUE TITLE
Name should be Validator Registry and not intkey

### ISSUE THREAD

**Issue by arsulegai** [manojgop/sawtooth-poet#22]
https://github.com/manojgop/sawtooth-poet/blob/aeeac4696efa1f70b104acbf82606d43a606c757/src/validator-registry-tp/src/main.rs#L45

**Comment by askmish** [comment]
Seems like the PR fixing this didn't go in while repo switching.

**Comment by arsulegai** [comment]
Ok, let's close this when it's fixed now in current repo. Otherwise again some miss will happen and we will lose tracking.

**Comment by askmish** [comment]
ok, I think PR7 would've fixed this.
