### ISSUE TITLE
Optimize desrialization done at multiple places

### ISSUE THREAD

**Issue by arsulegai** [manojgop/sawtooth-poet#25]
https://github.com/manojgop/sawtooth-poet/blob/aeeac4696efa1f70b104acbf82606d43a606c757/src/validator-registry-tp/src/validator_registry_payload.rs#L40

ValidatorRegistrySignupInfo parameter is read as string when ValidatroRegistryPayload is deserialized, it is later deserialized in getter method. These two steps can be combined, we will know if payload is not rightly composed at same step than distributing this knowledge at multiple places.

**Comment by askmish** [comment]
As per design.
