### ISSUE TITLE
Do these member variables need to be public, (this comment applies to other structs in VR TP as well)

### ISSUE THREAD

**Issue by arsulegai** [manojgop/sawtooth-poet#34]
https://github.com/manojgop/sawtooth-poet/blob/d737dadcf0dc8ac21781a27bbaa0ef36651852d8/src/validator-registry-tp/src/validator_registry_payload.rs#L31

**Comment by askmish** [comment]
yes, for the sake of serde.

**Comment by askmish** [comment]
And accessing the member as is.

**Comment by arsulegai** [comment]
Serde worked without member being public, I'm reopening this issue for code improvement tracking. We will try adding getters to access members instead of as is. Otherwise problem would be that any code in possession of this object can modify the contents of members.

**Comment by askmish** [comment]
We do not want setters/getters for structures here. This has been decided as per early designs.

**Comment by arsulegai** [comment]
Changed to protobuf
