### ISSUE TITLE
Do we need _method_name() convention in rust?

### ISSUE THREAD

**Issue by arsulegai** [manojgop/sawtooth-poet#35]
https://github.com/manojgop/sawtooth-poet/blob/9d13098eb4033554174e5df9026d143fdafa644d/src/validator-registry-tp/src/validator_registry_tp.rs#L139

**Comment by askmish** [comment]
Yes, we do that to indicate which method should be private in a struct.

**Comment by arsulegai** [comment]
Ok, thanks
